export const Amenities=[
    { label: 'Bar/Lounge', value: 'BAR/LOUNGE' },
    { label: 'Wedding Services', value: 'WEDDING SERVICES' },
    { label: 'Non-Smoking Rooms', value: 'NON-SMOKING ROOMS' },
    { label: 'Gym', value: 'GYM' },
    { label: 'Laundry Service', value: 'LAUNDRY SERVICE' },
    { label: 'Gym', value: 'GYM' },
    { label: 'Kids Club', value: 'KIDS CLUB' },
    { label: 'Sauna', value: 'SAUNA' },
    { label: 'Kids Club', value: 'KIDS CLUB' },
    { label: 'Valet Parking', value: 'VALET PARKING' },
    { label: 'Hot Tub', value: 'HOT TUB' },
    { label: '24/7 Front Desk', value: '24/7 FRONT DESK' },
    { label: 'Beach Access', value: 'BEACH ACCESS' },
    { label: 'Gym', value: 'GYM' },
    { label: 'Beach Access', value: 'BEACH ACCESS' },
    { label: 'Airport Shuttle', value: 'AIRPORT SHUTTLE' },
    { label: 'Babysitting', value: 'BABYSITTING' },
    { label: 'Concierge Service', value: 'CONCIERGE SERVICE' },
    { label: 'Gym', value: 'GYM' },
    { label: 'Sauna', value: 'SAUNA' },
    { label: 'Babysitting', value: 'BABYSITTING' },
    { label: 'Parking', value: 'PARKING' },
    { label: '24/7 Front Desk', value: '24/7 FRONT DESK' },
    { label: 'Bicycle Rentals', value: 'BICYCLE RENTALS' },
    { label: 'Tennis Courts', value: 'TENNIS COURTS' },
    { label: 'Pet-Friendly', value: 'PET-FRIENDLY' },
    { label: 'Room Service', value: 'ROOM SERVICE' },
    { label: 'Spa', value: 'SPA' },
    { label: 'Non-Smoking Rooms', value: 'NON-SMOKING ROOMS' },
    { label: 'Golf Course', value: 'GOLF COURSE' }
  ]